import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { Loader2, ShieldCheck, RefreshCw, Search } from 'lucide-react';
import toast from 'react-hot-toast';
import { raService } from '../../services/ra.service';
import { authService } from '../../services/auth.service';

const date = (value:string) => value ? new Date(value).toLocaleString('en-IN') : '—';
export default function RAIdentityAccessPanel({ selectedIds = [], onSaved, defaultOpen = false }: { selectedIds?:string[]; onSaved?:()=>void; defaultOpen?:boolean }) {
  const user = authService.getCurrentUser();
  const [open,setOpen] = useState(defaultOpen);
  const [requests,setRequests] = useState<any[]>([]);
  const [reason,setReason] = useState('');
  const [note,setNote] = useState('');
  const [search,setSearch] = useState('');
  const [statusFilter,setStatusFilter] = useState('All');
  const [loading,setLoading] = useState(false);
  const [busy,setBusy] = useState(false);
  const [clientRequest,setClientRequest] = useState<any|null>(null);
  const [approvedIds,setApprovedIds] = useState<Set<string>>(new Set());
  const openClients = (request:any) => {
    setClientRequest(request);
    setApprovedIds(new Set(request.clients?.filter((client:any)=>client.status==='Pending' && client.id).map((client:any)=>client.id)));
  };
  const [identity,setIdentity] = useState<{id:string;name:string;pan:string;aadhaar:string}|null>(null);
  const [confirm,setConfirm] = useState<{text:string;run:()=>Promise<void>}|null>(null);
  const load = async () => { setLoading(true); try { setRequests((await raService.getIdentityRequests()).map((request:any)=>({...request,client:request.client || {client_name:request.client_name}}))); } catch(e:any) { toast.error(e.response?.data?.error || 'Unable to load requests.'); } finally { setLoading(false); } };
  useEffect(()=>{if(defaultOpen)load();},[defaultOpen]);
  const execute = async () => {
    if (!confirm || busy) return;
    setBusy(true);
    try { await confirm.run(); setConfirm(null); await load(); window.dispatchEvent(new Event('ra-identity-updated')); }
    catch(e:any) { toast.error(e.response?.data?.error || 'Operation failed.'); }
    finally { setBusy(false); }
  };
  const filteredRequests = requests.filter(request => (statusFilter==='All' || request.status===statusFilter) && [request.clients?.map((client:any)=>client.name).join(' '),request.requester?.full_name,request.requester_role,request.branch?.name,request.reason].join(' ').toLowerCase().includes(search.toLowerCase()));
  const badge = (status:string) => status==='Pending'?'bg-amber-500/10 text-amber-500 border-amber-500/20':status==='Approved'?'bg-emerald-500/10 text-emerald-500 border-emerald-500/20':status==='Rejected'?'bg-rose-500/10 text-rose-500 border-rose-500/20':'bg-sky-500/10 text-sky-500 border-sky-500/20';
  return <div className="rounded-2xl border border-[var(--border)] bg-[var(--bg-card)] p-4 sm:p-6 space-y-5">
    <button onClick={()=>{setOpen(!open);if(!open)load();}} className="inline-flex gap-2 items-center font-semibold text-[var(--accent)]"><ShieldCheck className="w-5 h-5"/>PAN / Aadhaar Access Requests</button>
    {open && <>
      <p className="text-xs text-[var(--text-muted)]">Full identity details require admin approval. Permission remains available until the requester saves identity changes. History does not contain identity numbers.</p>
      {selectedIds.length > 0 && <div className="flex flex-wrap gap-3"><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required reason for viewing / editing identity" className="flex-1 min-w-64 px-3 py-2 rounded-xl bg-[var(--bg-base)] border border-[var(--border)]"/><button disabled={reason.trim().length<5} onClick={()=>{const ids=[...selectedIds];const why=reason;setConfirm({text:`Request permission to view and edit PAN/Aadhaar for ${ids.length} selected clients? Reason: ${why}`,run:async()=>{await raService.requestIdentityAccess(ids,why);setReason('');toast.success('Requests sent to admin.');}});}} className="px-4 py-2 rounded-xl bg-[var(--accent)] text-slate-950 disabled:opacity-50">Request for {selectedIds.length} clients</button></div>}
      <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{['Pending','Approved','Rejected','Consumed','Revoked'].map(status=><button key={status} onClick={()=>setStatusFilter(status)} className={`text-left p-4 rounded-xl border ${badge(status)}`}><span className="text-xs font-semibold uppercase tracking-wide">{status==='Consumed'?'Access completed':status}</span><div className="text-2xl font-bold mt-1 tabular-nums">{requests.filter(request=>request.status===status).length}</div></button>)}</div>
      <div className="flex flex-wrap items-center gap-3"><div className="relative flex-1 min-w-56"><Search className="absolute left-3 top-3 w-4 h-4 text-[var(--text-muted)]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search client, requester, branch or reason…" className="w-full pl-9 pr-3 py-2.5 rounded-xl bg-[var(--bg-base)] border border-[var(--border)] text-sm"/></div><select aria-label="Filter request status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="px-3 py-2.5 rounded-xl bg-[var(--bg-base)] border border-[var(--border)] text-sm">{['All','Pending','Approved','Rejected','Consumed','Revoked'].map(status=><option key={status} value={status}>{status==='All'?'All statuses':status==='Consumed'?'Access completed':status}</option>)}</select><button disabled={loading} onClick={load} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border border-[var(--border)] text-sm font-semibold"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Refresh</button></div>
      {user?.role==='admin' && <label className="block text-xs font-semibold text-[var(--text-secondary)]">Decision note <span className="font-normal text-[var(--text-muted)]">— applied to the next approval or rejection</span><textarea rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="Add verification details or a rejection reason…" className="block mt-2 w-full px-3 py-2 rounded-xl bg-[var(--bg-base)] border border-[var(--border)] text-sm"/></label>}
      <div className="overflow-auto rounded-xl border border-[var(--border)]"><table className="w-full text-sm text-left min-w-[1200px]"><thead className="bg-[var(--table-header-bg)] text-[var(--text-muted)] text-xs uppercase tracking-wide"><tr>{['Client','Requester / Role','Branch','Reason','Requested','Status','Verified by','Decision time / note','Identity saved','Action'].map(h=><th key={h} className="px-4 py-3 whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{filteredRequests.map(r=><tr key={r.id} className="border-t border-[var(--border)] hover:bg-[var(--bg-hover)] align-top"><td className="px-4 py-4 font-semibold">{r.client?.client_name}<button onClick={()=>openClients(r)} className="block mt-2 whitespace-nowrap text-xs font-medium text-[var(--accent)]">View clients</button></td><td className="px-4 py-4"><div className="font-medium">{r.requester?.full_name}</div><span className="inline-block mt-1 text-xs capitalize text-[var(--text-muted)]">{r.requester_role}</span></td><td className="px-4 py-4">{[...new Set(r.clients?.map((client:any)=>client.branch).filter(Boolean))].join(', ') || '—'}</td><td className="px-4 py-4 min-w-40 max-w-64 whitespace-normal break-words">{r.reason}</td><td className="px-4 py-4 text-xs whitespace-nowrap text-[var(--text-secondary)]">{date(r.requested_at)}</td><td className="px-4 py-4"><span className={`inline-flex px-2.5 py-1 rounded-full border text-xs font-semibold whitespace-nowrap ${badge(r.status)}`}>{r.status==='Consumed'?'Completed':r.status}</span></td><td className="px-4 py-4">{r.decider?.full_name || '—'}</td><td className="px-4 py-4 text-xs"><div className="whitespace-nowrap">{date(r.decided_at)}</div><p className="text-[var(--text-muted)] mt-1">{r.decision_note}</p>{r.revoked_at && <p className="text-rose-500 mt-1">Revoked: {date(r.revoked_at)}</p>}</td><td className="px-4 py-4 text-xs whitespace-nowrap">{date(r.consumed_at)}</td><td className="px-4 py-4">
        {user?.role==='admin' && r.status==='Pending' && r.requester_id!==user.id && <button onClick={()=>openClients(r)} className="px-3 py-2 rounded-lg text-xs font-semibold border border-emerald-500/20 bg-emerald-500/10 text-emerald-500 whitespace-nowrap">Review clients</button>}
        {r.requester_id===user?.id && r.status==='Approved' && <button onClick={()=>openClients(r)} className="px-3 py-2 rounded-lg text-xs font-semibold bg-[var(--accent-bg)] text-[var(--accent)] whitespace-nowrap">View approved clients</button>}
        {user?.role==='admin' && r.status==='Approved' && <button onClick={()=>setConfirm({text:`Revoke all remaining access in this request for ${r.requester?.full_name}? Only this requester is affected; other users keep their permissions.`,run:async()=>{await raService.revokeIdentityAccess(r.id);toast.success('Access revoked.');}})} className="px-3 py-2 rounded-lg text-xs font-semibold bg-rose-500/10 text-rose-500 border border-rose-500/20">Revoke access</button>}
      </td></tr>)}</tbody></table>{!filteredRequests.length && <div className="p-10 text-center text-[var(--text-muted)]"><ShieldCheck className="w-8 h-8 mx-auto mb-3 opacity-50"/><p>{loading?'Loading request history…':'No requests match your filters.'}</p></div>}</div>
      <p className="text-xs text-[var(--text-muted)]">Showing {filteredRequests.length} of {requests.length} requests · Identity numbers are never included in this history.</p>
    </>}
    {clientRequest && createPortal(<div className="fixed inset-0 z-[210] bg-black/60 flex items-center justify-center p-4"><div role="dialog" aria-modal="true" aria-label="Requested clients" className="bg-[var(--bg-card)] border border-[var(--border)] rounded-2xl max-w-2xl w-full overflow-hidden">
      <div className="p-6 border-b border-[var(--border)]"><h2 className="text-lg font-bold">{clientRequest.clients?.length || 0} requested clients</h2><p className="mt-1 text-sm text-[var(--text-muted)]">Requested by {clientRequest.requester?.full_name}</p></div>
      {user?.role==='admin' && clientRequest.status==='Pending' && clientRequest.requester_id!==user.id && <div className="px-6 py-4 border-b border-[var(--border)] space-y-2"><p className="text-sm text-[var(--text-secondary)]">Checked clients will be approved. Unchecked clients will be rejected.</p><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={approvedIds.size>0 && approvedIds.size===clientRequest.clients.filter((c:any)=>c.status==='Pending' && c.id).length} onChange={e=>setApprovedIds(e.target.checked?new Set(clientRequest.clients.filter((c:any)=>c.status==='Pending' && c.id).map((c:any)=>c.id)):new Set())}/>Select all pending clients</label></div>}
      <div className="max-h-[45vh] overflow-y-auto divide-y divide-[var(--border)]">{clientRequest.clients?.map((client:any,index:number)=><div key={client.id || index} className="px-6 py-4 flex items-center gap-3">
        {user?.role==='admin' && clientRequest.status==='Pending' && clientRequest.requester_id!==user.id && client.status==='Pending' && client.id && <input aria-label={`Approve ${client.name}`} type="checkbox" checked={approvedIds.has(client.id)} onChange={e=>setApprovedIds(previous=>{const next=new Set(previous);if(e.target.checked)next.add(client.id);else next.delete(client.id);return next;})}/>}
        <div className="flex-1 min-w-0"><p className="font-semibold break-words">{client.name}</p><p className="text-xs text-[var(--text-muted)] mt-1">{client.branch || 'No branch'}</p></div><span className={`px-2.5 py-1 rounded-full border text-xs ${badge(client.status)}`}>{client.status==='Consumed'?'Completed':client.status}</span>
        {clientRequest.requester_id===user?.id && client.status==='Approved' && client.id && <button onClick={()=>setConfirm({text:`Open approved identity for ${client.name}?`,run:async()=>{const value=await raService.getApprovedIdentity(client.id);setClientRequest(null);setIdentity({id:client.id,name:client.name,pan:value.pan || '',aadhaar:value.aadhaar_no || ''});}})} className="px-3 py-2 rounded-lg text-xs font-semibold bg-[var(--accent-bg)] text-[var(--accent)] whitespace-nowrap">View / edit</button>}
      </div>)}</div>
      <div className="p-6 border-t border-[var(--border)] flex flex-wrap justify-end items-center gap-3"><button onClick={()=>setClientRequest(null)} className="px-4 py-2 rounded-xl border border-[var(--border)]">Close</button>
        {user?.role==='admin' && clientRequest.status==='Pending' && clientRequest.requester_id!==user.id && <button onClick={()=>{const selected=[...approvedIds];const request=clientRequest;const decisionNote=note;const pending=request.clients.filter((c:any)=>c.status==='Pending').length;setConfirm({text:`Approve ${selected.length} clients and reject ${pending-selected.length} clients for ${request.requester?.full_name}? Only checked clients will receive view/edit permission.`,run:async()=>{await raService.decideIdentityRequest(request.id,true,decisionNote,selected);setClientRequest(null);toast.success(`${selected.length} clients approved; ${pending-selected.length} rejected.`);}});}} className="px-4 py-2 rounded-xl bg-[var(--accent)] text-slate-950 font-semibold">Confirm selection ({approvedIds.size} approved)</button>}
      </div>
    </div></div>,document.body)}
    {identity && createPortal(<div className="fixed inset-0 z-[220] bg-black/60 flex items-center justify-center p-4"><div role="dialog" aria-modal="true" aria-label="Edit approved identity" className="bg-[var(--bg-card)] border border-[var(--border)] rounded-2xl p-6 max-w-lg w-full space-y-4"><h2 className="font-bold text-lg">Identity: {identity.name}</h2><p className="text-xs">Saving closes this approval. A new request is required for future access.</p><label className="block">PAN<input value={identity.pan} maxLength={10} onChange={e=>setIdentity({...identity,pan:e.target.value.toUpperCase()})} className="block w-full px-3 py-2 rounded-xl bg-[var(--bg-base)]"/></label><label className="block">Aadhaar<input value={identity.aadhaar} maxLength={12} onChange={e=>setIdentity({...identity,aadhaar:e.target.value.replace(/\D/g,'')})} className="block w-full px-3 py-2 rounded-xl bg-[var(--bg-base)]"/></label><div className="flex justify-end gap-3"><button onClick={()=>setIdentity(null)}>Close</button><button onClick={()=>{const value={...identity};setConfirm({text:`Save PAN/Aadhaar changes for ${value.name}? This closes the approval and masks the details again.`,run:async()=>{await raService.saveApprovedIdentity(value.id,value.pan,value.aadhaar);setIdentity(null);onSaved?.();toast.success('Identity saved; approval closed.');}});}} className="px-4 py-2 rounded-xl bg-[var(--accent)] text-slate-950">Save identity changes</button></div></div></div>,document.body)}
    {confirm && createPortal(<div className="fixed inset-0 z-[230] bg-black/60 flex items-center justify-center p-4"><div role="dialog" aria-modal="true" aria-label="Confirm identity action" className="bg-[var(--bg-card)] border border-[var(--border)] rounded-2xl p-6 max-w-md w-full"><h2 className="font-bold text-lg">Confirm identity action</h2><p className="my-4 text-sm">{confirm.text}</p><div className="flex justify-end gap-3"><button disabled={busy} onClick={()=>setConfirm(null)}>Cancel</button><button disabled={busy} onClick={execute} className="px-4 py-2 rounded-xl bg-[var(--accent)] text-slate-950 inline-flex gap-2">{busy && <Loader2 className="w-4 h-4 animate-spin"/>}{busy?'Processing…':'Confirm'}</button></div></div></div>,document.body)}
  </div>;
}
