import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { parseRaCsv } from '../../frontend/src/utils/raCsv.ts';
import { normalizeRaImportRow, raClientDuplicateKeys } from '../src/utils/raImport.ts';

const sample = parseRaCsv(readFileSync(new URL('../../frontend/public/templates/ra-clients-sample.csv', import.meta.url), 'utf8'));
assert.equal(sample.length, 4);
const imported = normalizeRaImportRow(sample[0]!);
assert.equal(imported.amount, 1500);
assert.equal(imported.subscription_start_date, '2026-09-15');
assert.equal(imported.kra_updation_status, 'Completed');
const [row] = parseRaCsv('Client Name,Package,Fee Paid,Validity From,Validity To,KRA Status,Remarks\r\nExample,Basic,"₹1,500",15/09/2026,15/10/2026,completed,"Contains, comma"');
const result = normalizeRaImportRow(row!);
assert.equal(result.amount, 1500);
assert.equal(result.subscription_start_date, '2026-09-15');
assert.equal(result.subscription_end_date, '2026-10-15');
assert.equal(result.kra_updation_status, 'Completed');
assert.equal(result.remarks, 'Contains, comma');
assert.throws(() => parseRaCsv('client_name,package,amunt\nExample,Basic,1500'), /Unrecognized/);
assert.throws(() => parseRaCsv('client_name,package,amount\nExample,Basic,1,500'), /cells/);
assert.throws(() => parseRaCsv('client_name,package,amount,Fee Paid\nExample,Basic,0,1500'), /Conflicting/);
assert.throws(() => parseRaCsv('client_name,package\n"Example,Basic'), /unclosed/);
assert.throws(() => normalizeRaImportRow({amount:'abc'}), /Amount/);
assert.throws(() => normalizeRaImportRow({payment_date:'31/02/2026'}), /calendar/);
assert.throws(() => normalizeRaImportRow({subscription_start_date:'2026-10-15',subscription_end_date:'2026-09-15'}), /end date/);
assert.throws(() => normalizeRaImportRow({kra_updation_status:'Done'}), /KRA status/);
const [coverage] = parseRaCsv('client_name,package,amount,coverage_start_date,coverage_end_date\nExample,Elite,"INR 25,000.50",15/09/2026,15/10/2026');
const normalizedCoverage = normalizeRaImportRow(coverage!);
assert.equal(normalizedCoverage.amount, 25000.50);
assert.equal(normalizedCoverage.subscription_start_date, '2026-09-15');
assert.equal(normalizedCoverage.subscription_end_date, '2026-10-15');
assert.equal(normalizeRaImportRow({coverage_start_date:'15/09/2026',paid_amount:'₹1,50,000'}).amount, 150000);
assert.throws(() => normalizeRaImportRow({coverage_start_date:'2026-09-15',subscription_start_date:'2026-09-16'}), /Conflicting/);
const keys = raClientDuplicateKeys({client_name:' Example  Client ',mobile_number:'+91 98765 43210',pan:'abcde1234f',sw_code:'SW-001'});
assert.ok(keys.includes('pan:abcde1234f'));
assert.ok(keys.includes('sw:sw-001'));
assert.ok(keys.some(key => raClientDuplicateKeys({client_name:'example client',mobile_number:'9876543210'}).includes(key)));
assert.ok(!keys.some(key => raClientDuplicateKeys({client_name:'Different Client',mobile_number:'9876543210'}).includes(key)));
assert.ok(raClientDuplicateKeys({pan:'******234F',client_name:'Example'}).every(key => !key.startsWith('pan:')));
console.log('RA CSV import checks passed.');

const merged = parseRaCsv('client_name,package,coverage_start_date,subscription_start_date\nExample,Basic,,2026-09-15\nOther,Basic,2026-09-16,2026-09-16');
assert.equal(merged[0]!.subscription_start_date, '2026-09-15');
assert.equal(merged[1]!.subscription_start_date, '2026-09-16');
const conflicts: Array<{row:number,error:string}> = [];
const conflictPreview = parseRaCsv('client_name,package,coverage_start_date,subscription_start_date\nExample,Basic,2026-09-15,2026-09-16', (row,error) => conflicts.push({row,error}));
assert.equal(conflictPreview.length,1);
assert.equal(conflicts[0]!.row,2);
assert.match(conflicts[0]!.error, /coverage_start_date.*subscription_start_date/);
assert.match(conflicts[0]!.error, /not an existing client/);
