import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import { Loader2, Plus, Download, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import DashboardLayout from '../../components/layout/DashboardLayout';
import { franchiseService } from '../../services/franchise.service';
import type { FranchiseBootstrap, FranchiseSale } from '../../services/franchise.service';
import { ROUTES } from '../../constants/routes';
import { filterSales, periodRange, salesTotal, summarizeSales } from '../../utils/franchiseSalesReports';
import type { SalesPeriod } from '../../utils/franchiseSalesReports';
import FranchiseSalesUpload from './FranchiseSalesUpload';
import FranchiseSaleDialog from './FranchiseSaleDialog';
import FranchiseSalesChart from './FranchiseSalesChart';
import './franchise.css';
const money=(n:number)=>`₹${n.toLocaleString('en-IN',{maximumFractionDigits:2})}`;
export default function FranchiseSalesPortal({data,view='dashboard'}:{data:FranchiseBootstrap;view?:'dashboard'|'sales'|'reports'}) {
 const today=new Date().toISOString().slice(0,10);
 const [sales,setSales]=useState<FranchiseSale[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[showForm,setShowForm]=useState(false);
 const [branch,setBranch]=useState(''),[product,setProduct]=useState(''),[search,setSearch]=useState(''),[period,setPeriod]=useState<SalesPeriod>('all'),[anchor,setAnchor]=useState(today),[start,setStart]=useState(''),[end,setEnd]=useState('');
 useEffect(()=>{let active=true;franchiseService.getSales().then(r=>{if(active)setSales(r);}).catch(e=>{if(active)setError(e.response?.data?.message||'Could not load sales. Please refresh and try again.');}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 const range=period==='custom'?{start,end}:periodRange(period,anchor);
 const invalid=Boolean(range.start&&range.end&&range.start>range.end);
 const filtered=useMemo(()=>invalid?[]:filterSales(sales,{branch,product,search,...range}),[sales,branch,product,search,range.start,range.end,invalid]);
 const branchName=(id:string)=>data.directory.find(b=>b.id===id)?.location||'Unknown branch';
 const branchRows=useMemo(()=>summarizeSales(filtered,s=>s.franchise_id).map(r=>({...r,label:branchName(r.label)})),[filtered,data.directory]);
 const productRows=useMemo(()=>summarizeSales(filtered,s=>s.product),[filtered]);
 const trend=useMemo(()=>summarizeSales(filtered,s=>s.sale_date.slice(0,7)).sort((a,b)=>a.label.localeCompare(b.label)),[filtered]);
 const total=salesTotal(filtered);
 const description=`${period==='all'?'All dates':`${range.start||'Any start'} to ${range.end||'Any end'}`} · ${branch?branchName(branch):'All assigned branches'} · ${product||'All products'}${search?` · Customer: ${search}`:''}`;
 const pdf=()=>{try{const doc=new jsPDF({orientation:'landscape'});doc.setFontSize(20);doc.setTextColor(15,118,110);doc.text('MIS | Franchise Sales Report',14,18);doc.setFontSize(10);doc.setTextColor(40);doc.text(doc.splitTextToSize(description,265),14,28);doc.text(`Sales: ${filtered.length} | Revenue: INR ${total.toLocaleString('en-IN')} | Generated: ${today}`,14,44);
 const table=(title:string,head:string[],body:(string|number)[][],y?:number)=>{if(!y){doc.addPage();y=25;}doc.setFontSize(14);doc.text(title,14,y-5);autoTable(doc,{startY:y,head:[head],body,headStyles:{fillColor:[15,118,110]},styles:{fontSize:9},margin:{top:20,bottom:16}});};
 table('Branch-wise summary',['Branch','Sales','Revenue (INR)'],branchRows.map(r=>[r.label,r.count,r.amount.toFixed(2)]),58);table('Product-wise summary',['Product','Sales','Revenue (INR)'],productRows.map(r=>[r.label,r.count,r.amount.toFixed(2)]));table('Sales details',['Date','Branch','Customer','Product','Amount (INR)'],filtered.map(s=>[s.sale_date,branchName(s.franchise_id),s.customer_name,s.product,Number(s.amount).toFixed(2)]));for(let p=1;p<=doc.getNumberOfPages();p++){doc.setPage(p);doc.setFontSize(9);doc.text(`MIS Portal | ${p} / ${doc.getNumberOfPages()}`,14,doc.internal.pageSize.getHeight()-8);}doc.save(`franchise-sales-${today}.pdf`);}catch{toast.error('Could not generate PDF. Please try again.');}};
 const table=(title:string,headers:string[],rows:(string|number)[][])=><section className="fr-table-section"><div className="fr-panel-head"><h2>{title}</h2></div><div className="fr-table-wrap"><table className="fr-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={headers.length} className="fr-empty">No sales match these filters.</td></tr>}</tbody></table></div></section>;
 return <DashboardLayout><div className="fr-container"><header className="fr-header"><div><div className="fr-eyebrow">FRANCHISE MANAGEMENT</div><h1 className="fr-title">{view==='dashboard'?'Franchise sales dashboard':view==='sales'?'Product sales':'Sales reports'}</h1><p className="fr-subtitle">Track sales and revenue across your assigned branches.</p></div><div className="fr-toolbar">{view==='sales'?<button className="mis-btn mis-btn-primary" disabled={!data.directory.length||!data.access.canWrite} onClick={()=>setShowForm(true)}><Plus size={16}/>Add sale</button>:<Link className="mis-btn mis-btn-primary" to={ROUTES.FRANCHISE_SALES}>Product sales</Link>}{view==='dashboard'&&<Link className="mis-btn mis-btn-secondary" to={ROUTES.FRANCHISE_REPORTS}>View reports</Link>}<button className="mis-btn mis-btn-secondary" disabled={loading} onClick={async()=>{setLoading(true);setError('');try{setSales(await franchiseService.getSales());}catch{setError('Could not load sales. Please try again.');}finally{setLoading(false);}}}>Refresh</button></div></header>
 {error&&<p role="alert" className="fr-report-error">{error}</p>}
 {view==='sales'&&data.access.canWrite&&<FranchiseSalesUpload data={data} onSaved={created=>setSales(prev=>[...created,...prev])}/>}
 <section className="fr-panel fr-report-filters"><div className="fr-form fr-filters-grid"><div className="fr-form-group"><label htmlFor="fr-period">Period</label><select id="fr-period" value={period} onChange={e=>setPeriod(e.target.value as SalesPeriod)}>{[['all','All time'],['week','Week'],['month','Month'],['year','Year'],['custom','Custom dates']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></div>
 {period!=='all'&&period!=='custom'&&<div className="fr-form-group"><label htmlFor="fr-anchor">Date within selected {period}</label><input id="fr-anchor" type="date" value={anchor} onChange={e=>{if(e.target.value)setAnchor(e.target.value);}}/></div>}
 {period==='custom'&&<><div className="fr-form-group"><label htmlFor="fr-start">From date</label><input id="fr-start" type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div className="fr-form-group"><label htmlFor="fr-end">To date</label><input id="fr-end" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div></>}
 <div className="fr-form-group"><label htmlFor="fr-branch">Branch</label><select id="fr-branch" value={branch} onChange={e=>setBranch(e.target.value)}><option value="">All assigned branches</option>{data.directory.map(b=><option key={b.id} value={b.id}>{b.location} · {b.name}</option>)}</select></div><div className="fr-form-group"><label htmlFor="fr-product">Product</label><select id="fr-product" value={product} onChange={e=>setProduct(e.target.value)}><option value="">All products</option>{data.products.map(p=><option key={p}>{p}</option>)}</select></div><div className="fr-form-group"><label htmlFor="fr-search">Customer</label><input id="fr-search" placeholder="Search customer name" value={search} onChange={e=>setSearch(e.target.value)}/></div><button className="mis-btn mis-btn-secondary" onClick={()=>{setPeriod('all');setBranch('');setProduct('');setSearch('');setStart('');setEnd('');}}>Reset filters</button></div>{invalid&&<p role="alert" className="fr-report-error">End date must be on or after start date.</p>}</section>
 {loading?<p role="status" className="fr-empty"><Loader2 className="animate-spin inline"/> Loading sales…</p>:!error&&<div className={view==='reports'?'fr-print-report':''}><div className="fr-report-heading"><div><h2>{view==='reports'?'Franchise sales report':'Sales overview'}</h2><p>{description}</p></div>{view==='reports'&&<div className="fr-toolbar fr-no-print"><button className="mis-btn mis-btn-secondary" disabled={invalid||!filtered.length} onClick={()=>window.print()}><Printer size={16}/>Print</button><button className="mis-btn mis-btn-primary" disabled={invalid||!filtered.length} onClick={pdf}><Download size={16}/>Download PDF</button></div>}</div>
 <div className="fr-metrics-grid">{[['Assigned branches',branch?1:data.directory.length],['Product sales',filtered.length],['Sales revenue',money(total)],['Average sale',money(filtered.length?total/filtered.length:0)]].map(([label,value])=><div className="fr-metric-card" key={label}><div className="fr-metric-card-head">{label}</div><strong>{value}</strong></div>)}</div>
 {view==='dashboard'&&<><div className="fr-charts-grid"><FranchiseSalesChart title="Monthly sales revenue" rows={trend} type="line"/><FranchiseSalesChart title="Product revenue share" rows={productRows} type="doughnut"/></div><FranchiseSalesChart title="Branch performance" rows={branchRows}/></>}
 {view==='reports'&&<>{table('Branch-wise summary',['Branch','Sales','Revenue'],branchRows.map(r=>[r.label,r.count,money(r.amount)]))}{table('Product-wise summary',['Product','Sales','Revenue'],productRows.map(r=>[r.label,r.count,money(r.amount)]))}</>}
 {table(view==='dashboard'?'Recent sales (latest 10)':'Sales details',['Date','Branch','Customer','Product','Amount'],(view==='dashboard'?filtered.slice(0,10):filtered).map(s=>[s.sale_date,branchName(s.franchise_id),s.customer_name,s.product,money(Number(s.amount))]))}</div>}
 {showForm && <FranchiseSaleDialog data={data} onSaved={created=>setSales(previous=>[...created,...previous])} onClose={()=>setShowForm(false)}/>}
 </div></DashboardLayout>;
}
