/**
 * Centralized route paths for the application.
 * Use these constants instead of hardcoded strings in components.
 */
export const ROUTES = {
  LOGIN: '/login',
  FRANCHISE_LOGIN: '/franchise/login',
  FRANCHISE_DASHBOARD: '/franchise/dashboard',
  FRANCHISE_SALES: '/franchise/product-sales',
  FRANCHISE_REPORTS: '/franchise/reports',
  FRANCHISE_MANAGE: '/franchise/manage',
  DASHBOARD: '/dashboard',
  ADMIN_PANEL: '/admin-panel',
  PROFILE: '/profile',
  NOTIFICATIONS: '/notifications',
  DATA_ENTRY: '/data-entry',
  VERIFY_ENTRIES: '/verify-entries',
  IEPF_DATA_ENTRY: '/iepf-entry',
  IEPF_DASHBOARD: '/iepf-dashboard',
  SETTLEMENTS_DATA_ENTRY: '/settlements-entry',
  SETTLEMENTS_DASHBOARD: '/settlements-dashboard',
  KYC_DATA_ENTRY: '/kyc-entry',
  KYC_DASHBOARD: '/kyc-dashboard',
  DP_DATA_ENTRY: '/dp-entry',
  DP_DASHBOARD: '/dp-dashboard',
  IT_DATA_ENTRY: '/it-entry',
  IT_DASHBOARD: '/it-dashboard',
  FINANCE_DATA_ENTRY: '/finance-entry',
  FINANCE_DASHBOARD: '/finance-dashboard',
  COMPARISON: '/comparison/:dept',
  HR_DATA_ENTRY: '/hr-entry',
  HR_USER_MANAGEMENT: '/hr-users',
  SALES_DATA_ENTRY: '/sales-entry',
  SALES_DASHBOARD: '/sales-dashboard',
  RA_DASHBOARD: '/ra-dashboard',
  RA_DATA_ENTRY: '/ra-entry',
  RA_KYC: '/ra-kyc',
  RA_TESTIMONIALS: '/ra-testimonials',
  RA_REPORTS: '/ra-reports',
  RA_IDENTITY_HISTORY: '/ra-identity-history',
  TASKS: '/tasks',
  CREATOR_DASHBOARD: '/creator/dashboard',
  CREATOR_PLANNER: '/creator/planner',
  CREATOR_CALENDAR: '/creator/calendar',
  CREATOR_ASSETS: '/creator/assets',
  SMM_DASHBOARD: '/smm/dashboard',
  SMM_APPROVALS: '/smm/approvals',
  SMM_CAMPAIGNS: '/smm/campaigns',
  PRIVILEGE_DASHBOARD: '/privilege-dashboard',
  PRIVILEGE_DATA_ENTRY: '/privilege-entry',
  PRIVILEGE_REPORTS: '/privilege-reports',
  SW_GLOBAL_DASHBOARD: '/sw-global-dashboard',
  SW_GLOBAL_DATA_ENTRY: '/sw-global-entry',
  ROOT: '/',
} as const;

export type RoutePath = typeof ROUTES[keyof typeof ROUTES];
