const escape = (value: string) => value.replace(/[&<>"']/g, character => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[character]!));
export function franchiseCredentialEmail(email: string, name: string, franchise: string, frontendUrl: string) {
  const url = new URL('/login', frontendUrl);
  if (!['http:', 'https:'].includes(url.protocol)) throw new Error('Invalid frontend login URL.');
  const login = url.toString();
  const text = `Hello ${name},\n\nYour franchise ${franchise} is ready. Both logins are set up.\n\nLogin: ${login}\n\nEmployee login\nSelect role: Employee\nEmail: ${email}\nPassword: password123\nAdd customer product sales for assigned branches.\n\nOwner login\nSelect role: HOD\nEmail: ${email}\nPassword: password1234\nView assigned branches, reports and sales analytics.\n\nUse the same email for both logins and select the matching role. You can change your password in My Profile.\n\nMIS Portal`;
  const html = `<div style="background:#eef4f7;padding:28px 12px;font-family:Arial,sans-serif;color:#1e293b"><table role="presentation" style="width:100%;max-width:600px;margin:auto;border-collapse:collapse;background:#fff;border-radius:16px;overflow:hidden"><tr><td style="background:#152234;padding:28px;color:#fff"><span style="font-size:24px;font-weight:bold;color:#14b8a6">MIS Portal</span><div style="font-size:12px;margin-top:8px;color:#cbd5e1">FRANCHISE MANAGEMENT</div></td></tr><tr><td style="padding:28px"><h1 style="font-size:23px;margin-top:0">Your franchise logins are ready</h1><p>Hello ${escape(name)},</p><p>Both logins for <strong>${escape(franchise)}</strong> have been set up. Use the same email with the matching role and password below.</p><table style="width:100%;border-collapse:collapse;font-size:14px"><thead><tr style="background:#0f766e;color:#fff"><th style="padding:14px;text-align:left">Select role</th><th style="padding:14px;text-align:left">Email</th><th style="padding:14px;text-align:left">Password</th></tr></thead><tbody><tr style="background:#f0fdfa"><td style="padding:14px">Employee</td><td style="padding:14px;word-break:break-all">${escape(email)}</td><td style="padding:14px;font-weight:bold">password123</td></tr><tr style="background:#f1f5f9"><td style="padding:14px">HOD (Owner)</td><td style="padding:14px;word-break:break-all">${escape(email)}</td><td style="padding:14px;font-weight:bold">password1234</td></tr></tbody></table><p style="font-size:14px;line-height:1.6"><strong>Employee:</strong> add customer product sales.<br><strong>HOD / Owner:</strong> review assigned branches, reports and analytics.</p><p style="margin:26px 0"><a href="${escape(login)}" style="background:#0f766e;color:#fff;padding:14px 22px;border-radius:8px;text-decoration:none;font-weight:bold;display:inline-block">Open MIS login</a></p><p style="font-size:12px;color:#64748b">Login link: <a href="${escape(login)}">${escape(login)}</a><br>You can change your password in My Profile after signing in.</p></td></tr></table></div>`;
  return { text, html };
}
